import Link from "next/link";

export const metadata = { title: "Terms of Service – Proffy", description: "Terms and conditions for using Proffy." };

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg-base)", color: "var(--text-primary)", fontFamily: "var(--font-inter), system-ui, sans-serif" }}>
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "80px 32px" }}>
        <Link href="/" style={{ fontSize: "13px", color: "var(--text-muted)", textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "6px", marginBottom: "40px" }}>
          ← Back to Proffy
        </Link>

        <h1 style={{ fontSize: "2rem", fontWeight: 900, letterSpacing: "-0.03em", marginBottom: "8px" }}>Terms of Service</h1>
        <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "48px" }}>Last updated: April 2026</p>

        {[
          {
            title: "1. Acceptance",
            body: "By using Proffy, you agree to these terms. If you do not agree, do not use the service. These terms apply to all users of proffy.study and its sub-sites."
          },
          {
            title: "2. Service description",
            body: "Proffy is an AI-powered study assistant for students. It provides course-specific answers, study plans, flashcards, and exam preparation tools. The service is intended for educational use only."
          },
          {
            title: "3. User accounts",
            body: "You are responsible for maintaining the confidentiality of your account credentials. You must be at least 13 years old to use Proffy. You may not share your account with others or use it for commercial purposes."
          },
          {
            title: "4. Acceptable use",
            body: "You may not use Proffy to generate academic work intended to be submitted as your own without disclosure (academic fraud). You may not attempt to reverse-engineer, scrape, or abuse the service. Repeated prompt injection attempts may result in account suspension."
          },
          {
            title: "5. Content you upload",
            body: "You retain ownership of any course material you upload. By uploading, you grant Proffy a limited license to process and store it for the purpose of providing the service. You must only upload material you have the right to share."
          },
          {
            title: "6. AI accuracy",
            body: "Proffy AI answers are generated by large language models and may contain errors. Do not rely solely on Proffy for critical academic decisions. Always verify important information against your official course material."
          },
          {
            title: "7. Subscriptions and billing",
            body: "Paid plans are billed monthly. You may cancel at any time; cancellation takes effect at the end of the current billing period. We reserve the right to change pricing with 30 days notice."
          },
          {
            title: "8. Termination",
            body: "We reserve the right to suspend or terminate accounts that violate these terms, engage in abuse, or remain inactive for extended periods."
          },
          {
            title: "9. Limitation of liability",
            body: "Proffy is provided as-is. We are not liable for any academic outcomes, losses, or damages arising from use of the service."
          },
          {
            title: "10. Contact",
            body: "Questions about these terms? Email us at hello@proffy.study."
          },
        ].map(({ title, body }) => (
          <section key={title} style={{ marginBottom: "36px" }}>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700, marginBottom: "10px", color: "var(--text-primary)" }}>{title}</h2>
            <p style={{ fontSize: "15px", lineHeight: 1.7, color: "var(--text-secondary)" }}>{body}</p>
          </section>
        ))}
      </div>
    </div>
  );
}
